### PR TITLE
task(SDK - 3906) - Remove cross btn from five icons

### PR DESCRIPTION
**Pull request by Anush-Shand**
- Removes cross btn from five-icons
- Removes setOngoing(true) to make it non-sticky across all OS versions
- Deletes unused icon

### CODE REVIEW

**Review by piyush-kukadiya — CHANGES_REQUESTED** [review]
Remove close related changes from `PendingIntentFactory`

**Comment by piyush-kukadiya** [comment]
Update `CTPUSHTEMPLATES.md`

**Comment by piyush-kukadiya** [comment]
update `CTPUSHTEMPLATESANDROID12.md`

**Comment by piyush-kukadiya** [comment]
Crosscheck other places by performing global search on five icon related keywords.

**Comment by piyush-kukadiya** [comment]
Will old notifications dismiss after updating App with new SDK?

**Review by CTLalit — APPROVED** [review]

**Review by CTLalit — APPROVED** [review]

**Review by piyush-kukadiya — COMMENTED** [review]
LGTM

**Pull request merged**
